name: Podman

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  #schedule:
  #  - cron: '43 10 * * *'
  push:
    branches: [ "rocky-with-cockpit" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "rocky-with-cockpit" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}-cockpit
  # TODO: find a way to dinamically extract/derive tags
  TAG: latest


jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
      options: --privileged
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Setup Rocky container with all dependencies and settings
        run: |
          cat /etc/os-release
          dnf -y install which git podman buildah
          echo "/usr/sbin" >> $GITHUB_PATH
          echo "/usr/bin" >> $GITHUB_PATH
          echo "/usr/local/sbin" >> $GITHUB_PATH
          echo "/usr/local/bin" >> $GITHUB_PATH
          mkdir -p $HOME/.docker
          echo "{ \"auths\": {} }" > $HOME/.docker/config.json

      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # Login against a Docker registry except on PR
      # https://github.com/redhat-actions/podman-login
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          auth_file_path: /run/containers/0/auth.json

      # Build container image with buildah except on PR
      # https://github.com/redhat-actions/buildah-build
      - name: Build Container image
        id: build-image
        if: github.event_name != 'pull_request'
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          tags: ${{ env.TAG }}
          image: ${{ env.IMAGE_NAME }}

      # Push container image with podman except on PR
      # https://github.com/redhat-actions/push-to-registry
      - name: Push Container image
        id: push-image
        if: github.event_name != 'pull_request'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.REGISTRY }}
    
      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.build-image.outputs.tags }}
          DIGEST: ${{ steps.push-image.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:{}@${DIGEST}
